language: node_js
node_js:
  - "node"
  - "lts/*"
env:
  global:
    - NODE_ENV=development
before_install:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm test
after_success: npm run coverage